### ISSUE TITLE
Windows10 server not starting

### ISSUE THREAD

**Issue by alaniemieckota** [gocd/www.go.cd#312] opened 2016-07-20 14:34 UTC
I installed the go server and wanted to use it but the service and server not starting.
I did the installation with used of included java and without it.
With the included java i have : Could not reserve enough space for object heap

With my x64 java it displays info that ignores some memory setup options and then nothing happens

**Comment by arvindsv** [comment] 2016-08-02 18:52
Closing this. This is the repo for the website (go.cd). The repo for the actual GoCD server and agent is at https://github.com/gocd/gocd.

Maybe this issue is a duplicate of https://github.com/gocd/gocd/issues/2484, which was an issue with the Windows installer of 16.6.

If you can reproduce the problem with 16.7.0, please let us know there.

About the "Could not reserve enough space for object heap", I've seen that happen when asking for more than something like 1GB on a 32 bit Java. With 64-bit Java, it should work. The bundled JRE with 16.7.0 should work fine. Here's a [small video](https://dl.dropboxusercontent.com/u/2497296/Install_GoCD_on_Windows.mov) which shows it running on a vanilla Windows VM.

**Closed by arvindsv** 2016-08-02 18:52 UTC
