### ISSUE TITLE
sha256sum doesn't match for server

### ISSUE THREAD

**Issue by dminca** [gocd/www.go.cd#372] opened 2016-11-09 13:12 UTC
```
GOCD_VERSION="16.11.0" \
GOCD_BUILD="4185" \
CHECK="c8fa2dc52dd4797d8f2aa85823f8896dc4d89ee77b3b23925c93afd885080875" \
&& curl -sSL https://download.go.cd/binaries/${GOCD_VERSION}-${GOCD_BUILD}/generic/go-server-${GOCD_VERSION}-${GOCD_BUILD}.zip > go-server-${GOCD_VERSION}-${GOCD_BUILD}.zip \
&& echo "${CHECK} go-server-16.11.0-4185.zip" > sha256check \
&& sha256sum -c sha256check
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
```

**Comment by arvindsv** [comment] 2016-11-09 13:27
Looks ok to me. I checked just now. Closing this. It's probably a bad download. Happy to reopen if not.

```
$ curl -O https://download.go.cd/binaries/16.11.0-4185/generic/go-server-16.11.0-4185.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132M  100  132M    0     0  12.1M      0  0:00:10  0:00:10 --:--:-- 14.2M

$ ls -l
total 138,784,768
-rw-r--r-- 1 myuser staff 138,784,672 Nov  9 08:25 go-server-16.11.0-4185.zip

$ md5sum go-server-16.11.0-4185.zip
a6af7bd192ddb6fef72bd3d0f7c3232c  go-server-16.11.0-4185.zip

$ sha1sum go-server-16.11.0-4185.zip
e96a467663ff4f96535733ab8b2f3daafd708934  go-server-16.11.0-4185.zip

$ sha256sum go-server-16.11.0-4185.zip
c8fa2dc52dd4797d8f2aa85823f8896dc4d89ee77b3b23925c93afd885080875  go-server-16.11.0-4185.zip
```

![image](https://cloud.githubusercontent.com/assets/172235/20139911/5f076ff4-a656-11e6-9cc5-bee471a40096.png)

**Closed by arvindsv** 2016-11-09 13:27 UTC

**Comment by ketan** [comment] 2016-11-09 13:44
I think the problem is that the `echo > verify.sha256` uses a bad format. Single space, instead of two.

**Comment by dminca** [comment] 2016-11-09 13:47
Tried another way
```
/tmp # wget https://download.go.cd/binaries/16.11.0-4185/generic/go-server-16.11.0-4185.zip
Connecting to download.go.cd (52.85.184.141:443)
wget: error getting response: Connection reset by peer
/tmp # curl -O go-server-16.11.0-4185
/tmp # curl -O https://download.go.cd/binaries/16.11.0-4185/generic/go-server-16.11.0-4185.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  132M  100  132M    0     0  8960k      0  0:00:15  0:00:15 --:--:-- 6558k
/tmp # ls -l
total 135532
-rw-r--r--    1 root     root     138784672 Nov  9 13:45 go-server-16.11.0-4185.zip
/tmp # CHECK="c8fa2dc52dd4797d8f2aa85823f8896dc4d89ee77b3b23925c93afd885080875"
/tmp # echo "$CHECK go-server-16.11.0-4185.zip" | sha256sum -c -
sha256sum: WARNING: 1 of 1 computed checksums did NOT match
/tmp # echo $CHECK
c8fa2dc52dd4797d8f2aa85823f8896dc4d89ee77b3b23925c93afd885080875
```

**Comment by ketan** [comment] 2016-11-09 13:51
Try `echo $CHECK  go-server-16.11.0-4185.zip` with 2 spaces between $CHECK and the filename.

I'm going to fix the website to provide the right instructions.

**Comment by dminca** [comment] 2016-11-09 13:53
@ketan yup, it works in the container also now. It needed an extra space :smile:

**Comment by ketan** [comment] 2016-11-09 16:19
I've pushed a fix to the website, should be available in a few minutes on the download page.
